# **Day 7 — NumPy Fundamentals**

In [ ]:
import numpy as np

In [1]:
#Creating Arrays

import numpy as np

a = np.array([1, 2, 3])
b = np.arange(1, 10, 2)
c = np.zeros((2, 2))
d = np.ones((3, 3))
e = np.random.randint(10, 50, 5)

print("Array a:", a)
print("Array b:", b)
print("Zeros:\n", c)
print("Ones:\n", d)
print("Random Integers:", e)


Array a: [1 2 3]
Array b: [1 3 5 7 9]
Zeros:
 [[0. 0.]
 [0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Integers: [10 24 14 20 48]


In [2]:
#Array Attributes
arr = np.arange(1, 10)
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)


Array: [1 2 3 4 5 6 7 8 9]
Shape: (9,)
Dimensions: 1
Data type: int64
Size: 9


In [4]:
#Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("First three elements:", arr[:3])
print("Elements from index 2 to end:", arr[2:])


matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Element at row 1, col 2:", matrix[0,1])
print("First two rows:\n", matrix[:2])



First element: 10
Last element: 50
First three elements: [10 20 30]
Elements from index 2 to end: [30 40 50]
Element at row 1, col 2: 2
First two rows:
 [[1 2 3]
 [4 5 6]]


In [5]:
#Array Operations

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)



Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [6]:
#Aggregate Functions

arr = np.array([2, 4, 6, 8, 10])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Standard Deviation:", arr.std())


Sum: 30
Mean: 6.0
Max: 10
Min: 2
Standard Deviation: 2.8284271247461903


In [7]:
#Reshaping Arrays

arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print("Reshaped 3x3:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened array:", flattened)


Reshaped 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array: [1 2 3 4 5 6 7 8 9]


In [8]:
#Practice Exercises

#Create a NumPy array of numbers 1–20 and print even numbers only.
import numpy as np

arr = np.arange(1, 21)
even_nums = arr[arr % 2 == 0]
print("Even Numbers:", even_nums)


Even Numbers: [ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#Create a 3x3 matrix and find the sum of rows and columns.

matrix = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", matrix)
print("Row Sums:", matrix.sum(axis=1))
print("Column Sums:", matrix.sum(axis=0))


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Sums: [ 6 15 24]
Column Sums: [12 15 18]


In [10]:
#Generate 10 random numbers between 0–100 and find their mean and max.

rand_nums = np.random.randint(0, 101, 10)
print("Random Numbers:", rand_nums)
print("Mean:", np.mean(rand_nums))
print("Max:", np.max(rand_nums))


Random Numbers: [ 48 100  49  80  11  71  92  98  77  43]
Mean: 66.9
Max: 100


In [12]:
#Mini Project: “Basic Statistics Calculator”

import numpy as np

# Exam scores dataset
scores = np.array([78, 85, 92, 67, 88, 90, 76, 95, 89, 84])

print(" Exam Scores Statistics")
print("--------------------------")
print("Scores:", scores)
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Standard Deviation:", np.std(scores))
print("Range:", np.max(scores) - np.min(scores))


 Exam Scores Statistics
--------------------------
Scores: [78 85 92 67 88 90 76 95 89 84]
Mean: 84.4
Median: 86.5
Standard Deviation: 8.064738061462382
Range: 28
